// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szrwydtwuotpjjabltwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cnd5ZHR3dW90cGpqYWJsdHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjM3MjUsImV4cCI6MjA2OTM5OTcyNX0.Z_ArDVvp8LXW4N_NrDbqgr8q0Q-7vsbyESxAUt0yqVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});